---
title: "1_HU_MAYA_ALL"
author: "Melissa"
date: "16/08/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
inputDir="C:/Users/Melissa S/Desktop/PROJECTS/Brca1_Tumorigenesis/REVIEW/input/human/snRNAseq/All_cohorts/"
outputDir= "C:/Users/Melissa S/Desktop/PROJECTS/Brca1_Tumorigenesis/REVIEW/output/human"

##
RDatadir <- file.path(outputDir,"RData") ; if(!file.exists(RDatadir)){dir.create(RDatadir)}

QCdir <- file.path(outputDir, "QC") ; if(!file.exists(QCdir)){dir.create(QCdir)}
figDir= file.path(outputDir, "Figures") ; if(!file.exists(annotDir)){dir.create(annotDir)}
cnvDir= file.path(outputDir, "CNV") ; if(!file.exists(cnvDir)){dir.create(cnvDir)}
```

```{r}
library(ggExtra)
library(cowplot)
library(ggplot2)
library(Seurat)
library(dplyr)
```

```{r}
gtheme= theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 0, hjust = 0.5),axis.text.y = element_text(size=12, face="bold", colour = "black"),legend.text = element_text(face = "bold", size = 12),text=element_text(size=14, face="bold", colour = "black"))
###
themplot=theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank())

'%!in%' <- function(x,y)!('%in%'(x,y))
```

```{r}
seu=qs::qread(file.path(QCdir, "Raw_Seurat_Filtered.qs"))
df_all= seu@assays$RNA@counts
md_all=seu@meta.data
```



RUN MAYA ON ALL THE CELLS TO GET CELL ANNOTATION USING THE PANGLAO DATABASE
```{r}
memory.limit(size= 100000)
#MAYA ID prediction, use 'mammary gland' option, 
md_allH<-MAYA_predict_cell_types(expr_mat = df_all,
                                                 min_cells_pct = 0.05,
                                                 organs = "Mammary gland",
                                                 is_logcpm = FALSE,
                                                 plot_heatmap = F,
                                                 nCores = 1,
                                                 
                                                 compute_umap = T)
stopifnot(identical(rownames(md_allH$umap$layout), rownames(md_all)))
#Add the cell annotation to the metadata
md_all$MAYA_ID=  activity_summary_all_ID$clusters_annotation

l=list(md_allH, md_all)
qs::qsave(l, file.path(RDatadir, "List_MAYA_All_MdAll.qs"))
```

UMAP of TOTAL COUNT

UMAP ALL COLORED BY FEATURE :
```{r}


umap_custom <- as.data.frame(md_allH$umap$layout)
colnames(umap_custom)= c("UMAP_1","UMAP_2")

umap_custom$nGene=md_all$nFeature_RNA

png(paste0(figDir,"/UMAP_Total_cells_nGene.png"),height=2000, width = 2000,res=300)

p <- ggplot(umap_custom, aes(x =UMAP_1, y = UMAP_2, fill=nGene ))+ geom_point(size = 2.5, shape = 21,alpha=1) + theme_classic()  + NoAxes() +   scale_fill_viridis(option="B",limits = c(0.001, max(umap_custom$nGene)),  na.value= "grey",direction=-1) + NoLegend()
print(p)
dev.off()


umap_custom$nUMI=md_all$nCount_RNA

png(paste0(figDir,"/UMAP_Total_cells_nUMI.png"),height=2000, width = 2000,res=300)

p <- ggplot(umap_custom, aes(x =UMAP_1, y = UMAP_2, fill=nUMI ))+ geom_point(size = 2.5, shape = 21,alpha=1) + theme_classic() + NoLegend() + NoAxes() +   scale_fill_viridis(option="B",limits = c(1400, max(umap_custom$nUMI)),  na.value= "grey",direction=-1)
print(p)
dev.off()

###
library(ggpubr)
 leg1= as_ggplot(get_legend(ggplot(umap_custom, aes(x =UMAP_1, y = UMAP_2, fill=nGene ))+ geom_point(size = 2.5, shape = 21,alpha=1) + theme_classic()  + NoAxes() +   scale_fill_viridis(option="B",limits = c(0.001, max(umap_custom$nGene)),  na.value= "grey",direction=-1) ))
 
 leg2= as_ggplot(get_legend( ggplot(umap_custom, aes(x =UMAP_1, y = UMAP_2, fill=nUMI ))+ geom_point(size = 2.5, shape = 21,alpha=1) + theme_classic()  + NoAxes() +   scale_fill_viridis(option="B",limits = c(1400, max(umap_custom$nUMI)),  na.value= "grey",direction=-1)))

 pdf(file.path(figDir, "Legend_Human_UMAP_nGene_nUMI.pdf"))
 print(leg1)
 print(leg2)
 dev.off()
```



UMAP of all the populatio,s:
```{r}
col= rev(c(met.brewer(name="Renoir",n=6,type="discrete"),met.brewer(name="Austria",n=6,type="continuous")))
names(col)=unique(md_all$orig.ident)
##Other representation with non transparent circles, need shuffling to have a representation of all
umap_custom <- as.data.frame(md_allH$umap$layout)
colnames(umap_custom)= c("UMAP_1","UMAP_2")

metada_cells_col <- col[match(md_all$orig.ident,names(col))]
draw <- sample(1:dim(umap_custom)[1])





png(paste0(inputDir,"/Fig_Umap_All_SamplesF.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2, shape = 21,fill = metada_cells_col[draw],alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()
###
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ,fill = metada_cells_col[draw] ))+ geom_point(size = 4, shape = 21,alpha=1) + theme_classic() + theme(legend.position = "right") + scale_fill_manual(values= col)

  ## Save the legend ###
library(ggpubr)
 leg <- as_ggplot(get_legend(p))
pdf(file = paste0(inputDir, "/LEGEND_Fig_Umap_All_Samples.pdf"), width = 10, height = 10)
  print(leg)
dev.off()


#### ALL BRCA ####

col= col=c("BRCA mut"="darkgreen", "BRCA WT"="grey")
names(col)=unique(md_all$BRCA)
##Other representation with non transparent circles, need shuffling to have a representation of all
umap_custom <- as.data.frame(md_allH$umap$layout)

colnames(umap_custom)= c("UMAP_1","UMAP_2")

metada_cells_col <- col[match(md_all$BRCA,names(col))]
draw <- sample(1:dim(umap_custom)[1])

png(paste0(inputDir,"/Fig_Umap_All_BRCAF.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2, shape = 21,fill = metada_cells_col[draw],alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()
###
#type:
type= c("Fibroblasts"="#226B8F" ,      "Macrophages"= "#B54141", "Endothelial cells"="#C4C043",  "Luminal epithelial cells"=  "#8983A6", "T memory cells"= "#B54141", "Adipocytes"="orange", "Myoepithelial cells"="#8983A6" ,"Smooth muscle cells"="pink" )


##Other representation with non transparent circles, need shuffling to have a representation of all
umap_custom <- as.data.frame(md_allH$umap$layout)

colnames(umap_custom)= c("UMAP_1","UMAP_2")

metada_cells_col <- type[match(md_allH$cell_annotation,names(type))]
draw <- sample(1:dim(umap_custom)[1])

png(paste0(inputDir,"/Fig_Umap_All_TYPE.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2, shape = 21,fill = metada_cells_col[draw],alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()

p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ,fill = metada_cells_col[draw] ))+ geom_point(size = 4, shape = 21,alpha=1) + theme_classic() + theme(legend.position = "right") + scale_fill_manual(values= type)

  ## Save the legend ###
library(ggpubr)
 leg <- as_ggplot(get_legend(p))
pdf(file = paste0(inputDir, "/LEGEND_Fig_Umap_All_TYPE.pdf"), width = 10, height = 10)
  print(leg)
dev.off()

```


Table BRCA_Type:
```{r}
dt=as.data.frame(table(md_all$BRCA,md_all$MAYA_ID))

pdf(paste0(figDir, "/Barplot_ALL_BRCA.pdf"))
p <- ggplot(dt ,aes(x= Var2, y= Freq, fill= Var1))+ 
  geom_bar(stat="identity", position = "fill",show.legend = T,col="black",width=0.8) + scale_fill_manual(values=col)  + themplot
print(p)
dev.off()
md_all$type=ifelse(md_all$MAYA_ID %in% c("Luminal epithelial cells", "Myoepithelial cells"), "Epithelial", md_all$MAYA_ID)

dt=as.data.frame(table(md_all$BRCA,md_all$type))
pdf(paste0(figDir, "/Barplot_ALL_BRCA_2.pdf"))
p <- ggplot(dt ,aes(x= Var2, y= Freq, fill= Var1))+ 
  geom_bar(stat="identity", position = "fill",show.legend = T,col="black",width=0.8) + scale_fill_manual(values=col)  + themplot
print(p)
dev.off()
```