---
title: "Step3_2_CNVmatrixBinarization"
author: "Melissa"
date: "04/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
mainDir <- here::here() # the MainDir should be the root of Tumor_BRCA_P53:
source(knitr::purl(file.path(mainDir,"Scripts","global_var_current.Rmd"), quiet=TRUE))
source(knitr::purl(file.path(mainDir,"Scripts","scRNAseq_Functions.Rmd"), quiet=TRUE))
source(knitr::purl(file.path(mainDir,"Scripts","global_variables.Rmd"), quiet=TRUE))
```

## IF YOU WANT TO DRAW THE UMAP OF ALTERATIONS GO DIRETCLY TO THE SECOND SECTION BELOW TO DRAW IT AS THE EPITH ANNOTATED OBJECT HAS ALREADY GOT THE VALUES OF ALTERED GENOME PER CELL ##
```{r}
hd <- "/Users/equipe.soumelis/Desktop/BRCA1_tumor_mouse/scRNAseq/outputs/Seurat/CNVinference/Heatmaps"
obs1=read.table(file.path(ocntcnvDir,"/infercnv.observations.txt")) %>% as.matrix()
colnames(obs1) = gsub("[.]1","-1", colnames(obs1))
##
obs2=read.table(file.path(ostcnvDir,"/infercnv.observations.txt")) %>% as.matrix()
colnames(obs2) = gsub("[.]1","-1", colnames(obs2))
##
obs3=read.table(file.path(omtcnvDir,"/infercnv.observations.txt")) %>% as.matrix()
colnames(obs3) = gsub("[.]1","-1", colnames(obs3))
##
obs4=read.table(file.path(oltcnvDir,"/infercnv.observations.txt")) %>% as.matrix()
colnames(obs4) = gsub("[.]1","-1", colnames(obs4))
##
ref=read.table(file.path(ocntcnvDir, "infercnv.references.txt")) %>% as.matrix() #quantile same as CNTRL
colnames(ref) = gsub("[.]1","-1", colnames(ref))
###
cnt <- qs::qread(paste0(ocntcnvDir, "/CTRL_Seurat_InferCNV.qs"))
st <- qs::qread(paste0(file.path(ostcnvDir, "/ST_Seurat_InferCNV.qs")))
mt <- qs::qread(paste0(omtcnvDir, "/MT_Seurat_InferCNV.qs"))
lt <- qs::qread(paste0(oltcnvDir, "/LT_Seurat_InferCNV.qs"))
####### Load the inferCNV objects:
ic_cnt= readRDS(paste0(ocntcnvDir, "/run.final.infercnv_obj"))
ic_st= readRDS(paste0(ostcnvDir, "/run.final.infercnv_obj"))
ic_mt= readRDS(paste0(omtcnvDir, "/run.final.infercnv_obj"))
ic_lt= readRDS(paste0(oltcnvDir, "/run.final.infercnv_obj"))
#thresholds: taken control as ref:
lowthr <- quantile(obs1,0.1) #0.9120466 
highthr <- quantile(obs1,0.9)# 1.090948
```

```{r}
tlg <- obs3 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0)))) %>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_MT_WOBasal.qs"))
```

```{r}
tlg <- obs2 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0))))%>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_ST_WOBasal_SameThrasAll.qs"))
```


```{r}
tlg <- obs4 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0))))%>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_LT_WOBasal.qs"))
```


```{r}
obs= cbind(obs1,ref)
tlg <- obs %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0))))%>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_CNT_With_Basal.qs"))
```


#Start with the MT:
```{r}
tlg <- obs3 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0)))) %>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_MT_WOBasal.qs"))
###############
x= tlg %>% melt() %>% dplyr::filter(value==1)
x=as.data.frame.matrix(table(x$variable, x$value))
colnames(x)= "alt"
x= apply(x,2, function(u){round(u/nrow(tlg), 3)} ) %>% as.data.frame()
x$cell <- rownames(x)
###
mt= subset(mt, idents= c("Krt7+ MT","Odc1+ MT","Col1a2+ MT" ,"Dcn+ MT","S100a4+ MT", "Uck2+ MT" ,  "Klf2+ MT"))
x= x[match(colnames(mt), x$cell),]
stopifnot(rownames(x)== colnames(mt))
mt$altered_Genome <- x$alt
```

#ST:
```{r}
tlg <- obs2 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0))))%>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_ST_WOBasal_SameThrasAll.qs"))
###############

x= tlg %>% melt() %>% dplyr::filter(value==1)
x=as.data.frame.matrix(table(x$variable, x$value))
colnames(x)= "alt"
x= apply(x,2, function(u){round(u/nrow(tlg), 3)} ) %>% as.data.frame()
x$cell <- rownames(x)
###
x= x[match(colnames(st), x$cell),]
stopifnot(rownames(x)== colnames(st))
st$altered_Genome2 <- x$alt
```

#LT:
```{r}
tlg <- obs4 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0))))%>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_LT_WOBasal.qs"))
###############

x= tlg %>% melt() %>% dplyr::filter(value==1)
x=as.data.frame.matrix(table(x$variable, x$value))
colnames(x)= "alt"
x= apply(x,2, function(u){round(u/nrow(tlg), 3)} ) %>% as.data.frame()
x$cell <- rownames(x)
###
lt=subset(lt, idents= c("Meis2+ LT", "Clu+ LT",   "Apod+ LT",  "Mgp+ LT"))
x= x[match(colnames(lt), x$cell),]
stopifnot(rownames(x)== colnames(lt))
lt$altered_Genome <- x$alt
```


CNTRL
```{r}
obs= cbind(obs1,ref)
tlg <- obs %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0))))%>% abs()
qs::qsave(tlg, paste0(oaltDir, "/Binarized_CNT_With_Basal.qs"))
###############

x= tlg %>% melt() %>% dplyr::filter(value==1)
x=as.data.frame.matrix(table(x$variable, x$value))
colnames(x)= "alt"
x= apply(x,2, function(u){round(u/nrow(tlg), 3)} ) %>% as.data.frame()
x$cell <- rownames(x)

x= x[match(colnames(cnt), x$cell),]
stopifnot(rownames(x)== colnames(cnt))
cnt$altered_Genome <- x$alt
```

#################### Add it to the epith ########################

```{r}
s1 <- as.data.frame(st$subtype)
s1$alt= st$altered_Genome2
colnames(s1)= c("subtype","altered_Genome")
###
c1 <- as.data.frame(cnt$subtype)
c1$alt= cnt$altered_Genome
colnames(c1)= c("subtype","altered_Genome")
#####
m1 <- as.data.frame(mt$subtype)
m1$alt= mt$altered_Genome
colnames(m1)= c("subtype","altered_Genome")
#####
l1 <- as.data.frame(lt$subtype)
l1$alt= lt$altered_Genome
colnames(l1)= c("subtype","altered_Genome")
####
al=rbind(c1,s1,m1,l1)


p<- al %>% melt() %>% ggplot(aes(x=subtype, y=value, fill=subtype)) + geom_violin(show.legend = F) + scale_fill_manual(values= col) + themplot+gtheme + xlab("") + ylab("%Altered Genome") +theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 90))+ stat_summary(fun= median, geom='point', size = 8, colour = "white", shape = 95, show.legend = F)
##
ggsave(filename =paste0(altDir, "/Vln_CNT_ALLEpith_AltGenome.png"), device = "png", plot = p, width = 300, height = 300, dpi = 500, units = "mm" ) 
```

Add it the Epithelial seurat:
```{r}
epith=qs::qread(paste0(RDatadir, "/Epithelial_FinalAnnotation.qs"))
al=al[match(colnames(epith), rownames(al)),]
stopifnot(identical(rownames(al), colnames(epith)))
epith$alteredGenome= al$altered_Genome
###
p <- FeaturePlot(epith, "alteredGenome", pt.size = 1.5) + scale_color_viridis(option="B",limits = c(0.001, max(epith$alteredGenome)), na.value= "grey",direction=-1)
 p[[1]]$layers[[1]]$aes_params$alpha = 0.4
 #########
 ggsave(filename =paste0(altDir, "/UMAP_Epith_Altered_Genome.png"), device = "png", plot = p, width = 350, height = 300, dpi = 500, units = "mm" ) 
##
qs::qsave(epith, paste0(RDatadir, "/Epithelial_FinalAnnotation.qs"))
```

Take only the P16:
```{r}
p<- al %>% melt() %>% ggplot(aes(x=subtype, y=value, fill=subtype)) + geom_violin(show.legend = F) + scale_fill_manual(values= col) + themplot+gtheme + xlab("") + ylab("%Altered Genome") +theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 90))+ stat_summary(fun= median, geom='point', size = 8, colour = "white", shape = 95, show.legend = F)
##
ggsave(filename =paste0(altDir, "/Vln_CNT_ALLEpith_AltGenome.png"), device = "png", plot = p, width = 300, height = 300, dpi = 500, units = "mm" ) 
```

Recode the variable
```{r}
alm=al
alm$type= stringi::stri_sub(as.character(alm$subtype), from = -3, to= -1)
alm$type= dplyr::recode(alm$type, "sal"="Basal"," ST"="ST"," MT"="MT"," LT"="LT", "nal"="P16+ Pre-lesional")
##
alm=alm %>% dplyr::filter(type %in% c("LP","Basal","MT","ST","LT","P16+ Pre-lesional"))
###
alm$type= factor(alm$type, levels =  c("Basal","LP", "P16+ Pre-lesional", "ST", "MT","LT"))

###
p<- alm %>% reshape2::melt() %>% ggplot(aes(x=type, y=value, fill=type)) + geom_violin(show.legend = F) + scale_fill_manual(values= c("#1B9E77","#B06C1A","#ACEB0E","#9E2569" ,"#454545","#61A7D2")) + themplot+gtheme + xlab("") + ylab("%Altered Genome") +theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 90))+ stat_summary(fun= median, geom='point', size = 8, colour = "white", shape = 95, show.legend = F) + stat_compare_means(label = "p.signif", method = "wilcox.test", ref.group = "Basal",aes(label=..p.adj..))
#############
ggsave(filename =paste0(altDir, "/Vln_CNT_Transitioning_AltGenome.png"), device = "png", plot = p, width = 300, height = 300, dpi = 500, units = "mm" ) 

```




