---
title: "Step2_Pseudotime_1_PHATE"
author: "Melissa"
date: "6/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mainDir <- here::here() # the MainDir should be the root of Tumor_BRCA_P53:
source(knitr::purl(file.path(mainDir,"Scripts","global_var_current.Rmd"), quiet=TRUE))
source(knitr::purl(file.path(mainDir,"Scripts","scRNAseq_Functions.Rmd"), quiet=TRUE))
source(knitr::purl(file.path(mainDir,"Scripts","global_variables.Rmd"), quiet=TRUE))
```

#---------------------SKIP THIS PART ------------------------------#

The aim of this part is to run pseudotime using PHATE on the different compartments:

Subset the epithelial dataset on the clusters we want to run PHATE on :

```{r}
Idents(epith)="subtype"
DefaultAssay(epith)
seu= subset(epith, idents= c("LP","Avd","P16+ Pre-lesional", "Mki67+ ST","Cytl1+ ST","Fgf8+ ST","Spp1+ ST","Luminal H-S")) 
emb=Embeddings(seu, reduction = "umap") %>% as.data.frame()
#emb= emb %>% dplyr::filter(., UMAP_2 > (-10) & UMAP_2 < 5)
emb= emb %>% dplyr::filter(., UMAP_1 < (-4.8))
#emb= emb %>% dplyr::filter(., UMAP_2 > (-5) & UMAP_2 < 5 & UMAP_1 < (-3)) #only WO Lum HS
seu= subset(seu, cells= rownames(emb))
```

```{r}
##plot the New coordinates:

p=DimPlot(seu, cols = col[levels(Idents(seu))], pt.size = 4, label = F, label.box = F,raster=F) + NoAxes()  + NoLegend() + ggtitle("")
p[[1]]$layers[[1]]$aes_params$alpha = 0.7

png(filename =paste0(phateDir, "/Umap_Epith_Focus_TransitioningOnly_WOlegend.png"), height = 1000, width = 1000, res = 300 )
print(p)
dev.off()
##
leg=as_ggplot(get_legend(p))
pdf(file = paste0(phateDir, "/LEGENDS_Epith_Focus_Transitioning_SUBTYPE.pdf"), width = 5, height = 5)
  print(leg)
dev.off()
```


Run phate on the selected clusters;
```{r}
library(phateR)
reticulate::conda_list()
mat= t(seu@assays$RNA@data)
res.phate= phate(mat, ndim = 2, knn = 20, t=40, n.jobs = -2) 

seu[["PHATE"]] <- CreateDimReducObject(embeddings = res.phate$embedding, key = "PHATE_", assay = "RNA")
```
Save the PHATE coordinates:

```{r}
qs::qsave(seu, paste0(RDatadir, "/Transitioning_Seurat_WPhate.qs"))
```

###---------------------- START FROM HERE TO MAKE THE PLOTS --------------------------------------------###

```{r}
seu= qs::qread(paste0(RDatadir, "/Transitioning_Seurat_WPhate.qs"))
```


```{r}
pdf(paste0(phateDir, "/PhateWO_LTMT.pdf"), height = 10, width = 10)
   p=DimPlot(seu, group.by = "subtype", reduction = "PHATE", cols = col, pt.size = 2)+gtheme+ NoLegend() + ggtitle("") + NoAxes()  + geom_point(data= as.data.frame(seu[["PHATE"]]@cell.embeddings) , aes(x =PHATE_1, y = PHATE_2, fill= col[match(seu$subtype,names(col))]), shape = 21 ,stroke=0.5)
   print(p)
dev.off()


##Other representation with non transparent circles, need shuffling to have a representation of all
umap_custom <- as.data.frame(seu[["PHATE"]]@cell.embeddings)
metada_cells <- seu$subtype
metada_cells_col <- brca_cols$col[match(seu$subtype,names(brca_cols$col))]

draw <- sample(1:dim(umap_custom)[1])

png(paste0(phateDir,"/PhateWO_LTMT.png"),height=1000, width = 1000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =PHATE_1, y = PHATE_2 ))+ geom_point(size = 2, shape = 21,fill = metada_cells_col[draw],alpha=1) + themplot+ NoAxes()
print(p)
dev.off()
 
## Save the legend ###
 leg <- as_ggplot(get_legend(p))
pdf(file = paste0(phateDir, "/LEGEND_Umap_Epithelial_SUBTYPE.pdf"), width = 10, height = 10)
  print(leg)
dev.off()
```

