---
title: "0_HU_QC"
author: "Melissa"
date: "16/08/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
inputDir="C:/Users/Melissa S/Desktop/PROJECTS/Brca1_Tumorigenesis/REVIEW/input/human/snRNAseq/All_cohorts/"
outputDir= "C:/Users/Melissa S/Desktop/PROJECTS/Brca1_Tumorigenesis/REVIEW/output/human"

##
RDatadir <- file.path(outputDir,"RData") ; if(!file.exists(RDatadir)){dir.create(RDatadir)}

QCdir <- file.path(outputDir, "QC") ; if(!file.exists(QCdir)){dir.create(QCdir)}
figDir= file.path(outputDir, "Figures") ; if(!file.exists(annotDir)){dir.create(annotDir)}
cnvDir= file.path(outputDir, "CNV") ; if(!file.exists(cnvDir)){dir.create(cnvDir)}


```

```{r}
library(ggExtra)
library(cowplot)
library(ggplot2)
library(Seurat)
library(dplyr)
```

```{r}
gtheme= theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 0, hjust = 0.5),axis.text.y = element_text(size=12, face="bold", colour = "black"),legend.text = element_text(face = "bold", size = 12),text=element_text(size=14, face="bold", colour = "black"))
###
themplot=theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank())

'%!in%' <- function(x,y)!('%in%'(x,y))
```


```{r}
samplename=list.files(inputDir)
fmDir=file.path(inputDir,samplename ,"filtered_feature_bc_matrix")
rmDir=file.path(inputDir, samplename ,"raw_feature_bc_matrix")
#---------------------#
```




Create the seurat objects:

```{r}

for (i in seq (1, length(samplename))) {
  message(paste0("Creating Seurat Object for Sample: ", samplename[i]))
  assign(samplename[i], CreateSeuratObject(Read10X(fmDir[i]), project = samplename[i], min.cells = 20, min.features = 50)) 
}
gc()

seuratlist= mget(samplename)


invivo <- merge(x=seuratlist[[1]], y=seuratlist[c(2: length(seuratlist))])
qs::qsave(invivo , file.path(RDatadir, "merged_raw_invivo_HU.qs"))
invivo=qs::qread(file.path(RDatadir, "merged_raw_invivo_HU.qs"))
library(sceasy)

sceasy::convertFormat(invivo, from="seurat", to="anndata",
                       outFile= file.path(RDatadir,"invivoHU.h5ad"))

dt=as.data.frame(table(invivo$orig.ident))
colnames(dt)=c("sample", "#cells_Raw")
writexl::write_xlsx(dt, file.path(QCdir, "nbrCells_Raw_BeforeQC.xlsx"))
```

```{r}
for (i in c(4,5)) {
  message(paste0("Creating Seurat Object for Sample: ", samplename[i]))
  assign(samplename[i], CreateSeuratObject(Read10X(fmDir[i]), project = samplename[i], min.cells = 20, min.features = 50)) 
}
```




Create separate .h5ad objects from seurat objects for each sample
```{r}
seuratlist= mget(samplename)
 for(i in seq_len(length(seuratlist))){
   
   sceasy::convertFormat(seuratlist[[i]], from="seurat", to="anndata",
                       outFile= file.path(QCdir,paste0(names(seuratlist[i]),".h5ad")))
 }                
seuratlist=qs::qread(paste0(RDatadir, "/Seuratlist_Raw.qs"))
```



Read the doublet detection :
```{r}
doublet_detectionDir=file.path(QCdir, "doublet_detection")
doublet_file=list.files(doublet_detectionDir)
identical(samplename[-1], gsub(".h5ad_DoubletDetection.csv", "",doublet_file))

for(i in seq_len(length(samplename))){
  assign(paste0(gsub(".h5ad_DoubletDetection.csv", "",doublet_file[i]), "_doublet"), read.csv(file.path(doublet_detectionDir, doublet_file[i]), row.names = 1)) %>% as.data.frame()
}
```

```{r}
identical(rownames(get(paste0(names(seuratlist[1]), "_doublet"))[colnames(seuratlist[[1]]),]), colnames(seuratlist[[1]]))
          
for(i in seq_len(length(seuratlist))){
  seuratlist[[i]]= AddMetaData(seuratlist[[i]],get(paste0(names(seuratlist[i]), "_doublet"))[colnames(seuratlist[[i]]),])
  
}          
qs::qsave(seuratlist, file.path(RDatadir, "Seurat_List_Raw_WDoubletDetection.qs"))

seuratlist_raw=qs::qread(file.path(RDatadir2, "Seurat_List_Raw_WDoubletDetection.qs"))
seuratlist_raw$J_AG0377_hu_nuclei= merge(seuratlist_raw$J_AG0377_hu_nuclei_m06y22_3v3, seuratlist_raw$J_AG0377_hu_nuclei_m10y22)
grep("J_AG0377", names(seuratlist_raw))
#"

seuratlist_raw$J_AI4518_hu_nuclei= merge(seuratlist_raw$J_AI4518_hu_nuclei_m06y22_3v3, seuratlist_raw$J_AI4518_hu_nuclei_m10y22)
grep("J_AI4518_", names(seuratlist_raw))

seuratlist_raw=seuratlist_raw[-c(13,14,15,16)]

qs::qsave(seuratlist_raw, file.path(RDatadir, "Seurat_List_Raw_WDoubletDetection_WODuplicateSamples.qs"))
seuratlist=qs::qread(file.path(RDatadir, "Seurat_List_Raw_WDoubletDetection_WODuplicateSamples.qs"))
```


```{r}
seuratlist=seuratlist_raw

for(i in seq(1:length(seuratlist))){
  seuratlist[[i]][["percent.mito"]] <- PercentageFeatureSet(seuratlist[[i]], pattern = "^MT-")
}

features= c("nCount_RNA", "nFeature_RNA", "percent.mito")
pdf(paste0(QCdir, "/VlnPlot_Samples_BeforeQC.pdf") 
   , height = 8, width = 8)
 for(i in seq(1,length(seuratlist))){
p=VlnPlot(seuratlist[[i]], features= features)
print(p)
 }
 dev.off()
 #####################
 pdf(paste0(QCdir, "/VlnPlot_Samples_BeforeQC_Doublet.pdf") 
   , height = 8, width = 8)
 for(i in seq(1,length(seuratlist))){
p=VlnPlot(seuratlist[[i]], features= features, group.by = "doublet") + ggtitle(names(seuratlist)[i])
print(p)
 }
 dev.off()
```

Apply QC filters:

```{r}
#remove samples with few cells: 200 cells min
seuratlist=seuratlist[-c(8,10,11,12)]

#remove doublets:
for(i in seq(1:length(seuratlist))){
  seuratlist[[i]]<- subset(seuratlist[[i]], doublet=="0")
}
dt$sample=rownames(dt)

#for samples with too many cells apply rude filters:
seuratlist[[2]]<- subset(seuratlist[[2]], nFeature_RNA < 6000 & nFeature_RNA > 2500  & nCount_RNA < 50000 & percent.mito < 10)

seuratlist[[14]]<- subset(seuratlist[[14]], nFeature_RNA < 6000 & nFeature_RNA > 1200  & nCount_RNA < 50000 & percent.mito < 10)


seuratlist[[13]]<- subset(seuratlist[[13]], nFeature_RNA < 6000 & nFeature_RNA > 1200  & nCount_RNA < 50000 & percent.mito < 10)

seuratlist[[10]]<- subset(seuratlist[[10]], nFeature_RNA < 6000 & nFeature_RNA > 1500  & nCount_RNA < 50000 & percent.mito < 10)


for(i in c(1,3,4:9, 11,12,15:21)){
   seuratlist[[i]]<- subset(seuratlist[[i]], nFeature_RNA < 6000 & nFeature_RNA > 300 
                            & nCount_RNA < 50000  
                                  & percent.mito < 20)
}

qs::qsave(seuratlist, paste0(RDatadir, "/Seuratlist_postQC_spePerSample_F.qs"))
seuratlist=qs::qread(paste0(RDatadir, "/Seuratlist_postQC_spePerSample_F.qs"))

   



 for(i in seq(1:length(seuratlist))){
  seuratlist[[i]]<- seuratlist[[i]] %>%  SCTransform( method = "glmGamPoi",  verbose = FALSE,return.only.var.genes=TRUE) }
gc()

seuratlist$J_AG0377_hu_nuclei$orig.ident= "J_AG0377_hu_nuclei"
seuratlist$J_AI4518_hu_nuclei$orig.ident= "J_AI4518_hu_nuclei"

qs::qsave(seuratlist, paste0(RDatadir, "/Seuratlist_postQC_spePerSample_PostSCT_F.qs"))
  seuratlist=qs::qread(paste0(RDatadir, "/Seuratlist_postQC_spePerSample_PostSCT_F.qs"))

```



```{r}
seu=qs::qread(paste0(RDatadir, "/AllSamples_SCT_NoIntegration.qs"))
seu$orig.ident= ifelse(seu$orig.ident=="J_AG0377_hu_nuclei_m06y22_3v3",     "J_AG0377_hu_nuclei_m10y22",as.character(seu$orig.ident))
df_all=  seu

seed=123
COI <- NULL #cells of interest
max_cell <- 3000
for(i in 1:12){
  test <- subset(df_all, orig.ident==names(table(df_all$orig.ident))[i])
  
  if(dim(test)[2]>max_cell)  {
    subset_cell <- sample(x = colnames(test), size = max_cell)
  
  }else{
  subset_cell <- colnames(test)
}
COI <- c(COI,subset_cell)

}
```


```{r}
df_all <- subset(df_all, cells = COI)
meta_all <- df_all@meta.data

mat=df_all

meta_all$histology= meta_all$orig.ident
meta_all$histology=dplyr::recode(meta_all$histology, "J_665816H_hu_nuclei_m10y22" ="BRCA mut", 
"J_665839H_hu_nuclei_m10y22"="BRCA mut",   "J_676187H_hu_nuclei_m10y22" ="BRCA mut",  "J_AA1532_hu_nuclei_m06y22" ="BRCA mut",  
 "J_AK9821_hu_nuclei_m01y23"="BRCA WT"  ,  "J_AL9487_hu_nuclei_m02y23"="BRCA WT",    "J_AM4078_hu_nuclei_m01y23" ="BRCA WT",  
 "J_AM6640_hu_nuclei_m02y23"="BRCA WT",    "J_AN7121_hu_nuclei_m02y23"="BRCA WT",    "J_AN9636_hu_nuclei_m02y23"="BRCA WT",   
 "SA_AB_5301"  ="BRCA mut",                 "SA_AD_1766" ="BRCA mut",                  "SA_AD_8557"="BRCA mut",                  
 "SA_AG_5988" ="BRCA mut",                  "J_AG0377_hu_nuclei_m10y22" ="BRCA mut",          "J_AI4518_hu_nuclei_m10y22"="BRCA mut", "J_667622H_hu_nuclei_m10y22"="BRCA mut", "J_678330H_hu_nuclei_m07y22" ="BRCA mut", "SA_AB_2047"="BRCA mut" ,"GPro_AW6196_hu_nuclei_m02y23"="BRCA mut" , "GPro_AX0503_hu_nuclei_m02y23"="BRCA mut" ,  "J_AE4734_hu_nuclei_m06y22_3v3"= "BRCA mut")

qs::qsave(df_all, file.path(QCdir, "Raw_Seurat_Filtered.qs"))
```
