---
title: "4_HU_MAYA_PAL"
author: "Melissa"
date: "17/08/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
inputDir="C:/Users/Melissa S/Desktop/PROJECTS/Brca1_Tumorigenesis/REVIEW/input/human/snRNAseq/All_cohorts/"
outputDir= "C:/Users/Melissa S/Desktop/PROJECTS/Brca1_Tumorigenesis/REVIEW/output/human/public_data/PAL"

##
RDatadir <- file.path(outputDir,"RData") ; if(!file.exists(RDatadir)){dir.create(RDatadir)}

figDir= file.path(outputDir, "Figures") ; if(!file.exists(annotDir)){dir.create(annotDir)}
cnvDir= file.path(outputDir, "CNV") ; if(!file.exists(cnvDir)){dir.create(cnvDir)}
```

```{r}
library(ggExtra)
library(cowplot)
library(ggplot2)
library(Seurat)
library(dplyr)
```

```{r}
gtheme= theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 0, hjust = 0.5),axis.text.y = element_text(size=12, face="bold", colour = "black"),legend.text = element_text(face = "bold", size = 12),text=element_text(size=14, face="bold", colour = "black"))
###
themplot=theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank())

'%!in%' <- function(x,y)!('%in%'(x,y))
```

ALL EPITHELIAL

```{r}
nepith= qs::qread(file.path(RDatadir,"Normal_EpithelialCompartments.qs"))
all= qs::qread(file.path(RDatadir,"Preneoplastic_and_NulliparousNormal_AllCompartments.qs"))

df_all= nepith@assays$RNA@counts
library(MAYA)
#MAYA on hallmark
memory.limit(size= 100000)
activity_summary_allN<-MAYA_pathway_analysis(expr_mat=df_all,
                                        modules_list = "hallmark",
                                        is_logcpm=F,min_cells_pct = 0.0)
gc()
qs::qsave(activity_summary_allN, file.path(RDatadir, "activity_summary_NormalEpithAll_Hallmark.qs"))
#qs::qsave(activity_summary_all, file.path(RDatadir, "activity_summary_all.qs"))

#MAYA ID prediction, use 'mammary gland' option, 
memory.limit(size= 100000)
activity_summary_all_IDN<-MAYA_predict_cell_types(expr_mat = df_all,
                                                 min_cells_pct = 0.05,
                                                 organs = "Mammary gland",
                                                 is_logcpm = FALSE,
                                                 nCores = 1,
                                                 plot_heatmap=FALSE,
                                                 compute_umap = TRUE)


lN=list(activity_summary_allN, activity_summary_all_IDN)

qs::qsave(lN, file.path(RDatadir, "MAYA_ID_PAL_NORMAL_AllEpith_nnEquil.qs"))
```


```{r}
col=c("Normal BRCA1+/- pre-neoplastic"="darkgreen", "Normal"="grey","Triple negative (BRCA1) tumor"="#183B0F")
umap_custom <- as.data.frame(activity_summary_allN$umap$layout)
colnames(umap_custom)= c("UMAP_1","UMAP_2")

metada_cells_col <- col[match(nepith$Condition,names(col))]
draw <- sample(1:dim(umap_custom)[1])


png(paste0(figDir,"/Fig_PAL_Umap_Epith_Condition.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom, aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2.5, shape = 21,fill = metada_cells_col,alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()

png(paste0(figDir,"/Fig_PAL_Umap_Epith_Condition_RandomSampling.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2.5, shape = 21,fill = metada_cells_col[draw],alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()

```

Plot the type information umap:
```{r}
col=c("N_LP"= "#F27ECB","N_ML"= "#F0BDED" , "N_Basal"= "#D8B2ED")
                  
                  
umap_custom <- as.data.frame(activity_summary_allN$umap$layout)
colnames(umap_custom)= c("UMAP_1","UMAP_2")

metada_cells_col <- col[match(nepith$subtype,names(col))]
draw <- sample(1:dim(umap_custom)[1])


png(paste0(figDir,"/Fig_PAL_Umap_Epith_Subtype.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom, aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2.5, shape = 21,fill = metada_cells_col,alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()

png(paste0(figDir,"/Fig_PAL_Umap_Epith_Subtype_RandomSampling.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2.5, shape = 21,fill = metada_cells_col[draw],alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()
```

focus on epithelial:
```{r}
meta_all=all@meta.data
meta_all$cell_annotation= activity_summary_all_IDN$cell_annotation



selection <- rownames(meta_all[meta_all$cell_annotation %in% c("Luminal epithelial cells","Myoepithelial cells","Epithelial cells"),])

sub_meta <- meta_all[rownames(meta_all) %in% selection,]



df_epithelial <- df_all[,selection]
meta_epithelial <- sub_meta


activity_summary_subset<-MAYA_pathway_analysis(expr_mat=df_epithelial,
                                            modules_list = "hallmark",
                                            is_logcpm=F)

gc()



qs::qsave(activity_summary_subset, file.path(RDatadir, "Subset_Epith_MAYA_Hallmark.qs"))


col=c( "Luminal epithelial cells"= "#F27ECB","Epithelial cells" ="#F27ECB" ,"Myoepithelial cells"= "#D8B2ED")


umap_custom <- as.data.frame(activity_summary_subset$umap$layout)
colnames(umap_custom)= c("UMAP_1","UMAP_2")

metada_cells_col <- col[match(sub_meta$cell_annotation,names(col))]
draw <- sample(1:dim(umap_custom)[1])


png(paste0(figDir,"/Fig_Umap_EMBO_EPITH_MAYA_TYPE_FromAll.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2.5, shape = 21,fill = metada_cells_col[draw],alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()
```



```{r}
col=c("Normal BRCA1+/- pre-neoplastic"="darkgreen","Normal"="grey")
umap_custom <- as.data.frame(activity_summary_subset$umap$layout)
colnames(umap_custom)= c("UMAP_1","UMAP_2")

metada_cells_col <- col[match(sub_meta$Condition,names(col))]
draw <- sample(1:dim(umap_custom)[1])


png(paste0(figDir,"/Fig_Umap_EMBO_EPITH_MAYA_BRCA_FromAll.png"),height=2000, width = 2000,res=300)
p <- ggplot(umap_custom[draw,], aes(x =UMAP_1, y = UMAP_2 ))+ geom_point(size = 2.5, shape = 21,fill = metada_cells_col[draw],alpha=1) + theme_classic() + NoLegend() + NoAxes()
print(p)
dev.off()
```


Launch the CNVs
```{r}
cells=colnames(activity_summary_allN$activity_matrix)
activity_summary_allN=qs::qread(file.path(RDatadir, "MAYA_ID_PAL_NORMAL_AllEpith_nnEquil.qs"))[[1]]
length(intersect(cells, colnames(nepith)))

so= subset(nepith, Condition %in% c("Normal", "Normal BRCA1+/- pre-neoplastic" ))
sall=qs::qread(file.path(RDatadir, "MAYA_ID_PAL_AllCompartments.qs"))[[2]]

endo= colnames(sall$activity_matrix[, which(sall$cell_annotation == "Endothelial cells"  )])

cnvr= subset(all, cells= endo)
cnvr$subtype= "Endothelial"
cnvo=merge(cnvr, nepith)

infer= subset(cnvo, Condition %in% c("Normal", "Normal BRCA1+/- pre-neoplastic" ))


tst= sample(rownames(infer@meta.data[which(infer@meta.data$Condition=="Normal"),]), 7785)

tst2= rownames(infer@meta.data[which(infer@meta.data$Condition=="Normal BRCA1+/- pre-neoplastic"),])

infer2= subset(infer, cells=c(tst, tst2))

stroma= sample(rownames(infer2@meta.data[which(infer2@meta.data$subtype=="Endothelial"),]), 1000)

ep= rownames(infer2@meta.data[which(infer2@meta.data$subtype %in% c("N_Basal", "N_LP", "N_ML")),])


cells=c(stroma, ep)
infer=subset(infer2, cells=cells)




set.seed(123)
bsl= sample(rownames(infer@meta.data[which(infer@meta.data$subtype=="N_Basal"),]), 1000)
stroma= sample(rownames(infer@meta.data[which(infer@meta.data$subtype=="Endothelial"),]), 800)
ml= sample(rownames(infer@meta.data[which(infer@meta.data$subtype=="N_ML"),]), 1000)
lp= rownames(infer@meta.data[which(infer@meta.data$subtype=="N_LP"),])

cells= c(bsl, stroma, ml,lp )
seu= subset(infer, cells = cells)

qs::qsave(seu, file.path(RDatadir, "Pal_Seurat_forCNV.qs"))
seu=qs::qread(file.path(RDatadir, "Pal_Seurat_forCNV.qs"))

##RUN INFER CNV
Idents(seu)="subtype"


cnv=Wrapper_inferCNV(seu,ref_group= "Endothelial",outputPath=cnvDir, analysis_mode="samples",HMM_type="i3", gene_annot = gene_annot) 
```


CNV of PAL ONLY EPITHELIAL:
```{r}
cnvo=readRDS( file.path(cnvDir, "run.final.infercnv_obj"))

mat=cnvo@expr.data
ref=mat[,cnvo@reference_grouped_cell_indices$Endothelial] %>% colnames()

obs=as.data.frame()

altpal= qs::qread(file.path(cnvDir, "CNVcellsPAL.qs"))

altpal=altpal[-which(altpal$cell %in% ref),]

bsl=cnvo@observation_grouped_cell_indices$N_Basal
lp=cnvo@observation_grouped_cell_indices$N_LP
ml=cnvo@observation_grouped_cell_indices$N_ML

length(intersect(colnames(all), gsub('.{2}$', '', cells)))



 seu= subset(nepith, cells =  gsub('.{2}$', '', altpal$cell))
 altpal$cell=gsub('.{2}$', '', altpal$cell)
 
 altpal=altpal %>% dplyr::filter(cell %in% colnames(seu))
identical(colnames(seu), altpal$cell)

seu$alt=altpal$alt

seu$class= paste0(seu$subtype, "_", seu$Condition)
####

dt=data.frame("class"= seu$class, "alt"=seu$alt)

dt2=aggregate(dt[,-1], by=list(dt$class), median) %>% as.data.frame()

dt3=aggregate(dt[,-1], by=list(dt$class), FUN = function(i) quantile(i, probs = 0.9, na.rm = T)) %>% as.data.frame()

pairwise.wilcox.test(dt$alt, dt$class)

dt4= cbind(dt2, dt3)

######
lp=mat[,cnvo@observation_grouped_cell_indices$N_LP] %>% colnames()
altpal=altpal[which(altpal$cell %in% lp),]

####

p=VlnPlot(seu, features = "alt", group.by = "subtype", split.by= "Condition", cols =c("Normal BRCA1+/- pre-neoplastic"="darkgreen", "Normal"="grey"), pt.size = 0) + NoLegend() + 
  stat_summary(fun= median, geom='point', size = 3, colour = "black", shape = 95)

pdf(file.path(figDir, "Pal_VlnPlot_Alteration.pdf"))
print(p)
dev.off()

######
dm= data.frame("class"=seu$class, "alt"=seu$alt)

dm$class=dplyr::recode(dm$class,  "N_Basal_Normal" ="N_Basal_Normal BRCA1+/- pre-neoplastic", "N_Basal_Normal BRCA1+/- pre-neoplastic"=  "N_Basal_Normal", "N_ML_Normal"  ="N_ML_Normal BRCA1+/- pre-neoplastic" , "N_ML_Normal BRCA1+/- pre-neoplastic" = "N_ML_Normal","N_LP_Normal"  = "N_LP_Normal BRCA1+/- pre-neoplastic" , "N_LP_Normal BRCA1+/- pre-neoplastic" = "N_LP_Normal")

p=dm %>% reshape2::melt() %>% ggplot(aes(x= class, y= value )) + geom_violin() + 
  stat_summary(fun= median, geom='point', size = 3, colour = "black", shape = 95)+ themplot + coord_flip() 
```

check pairwise cell correlation

```{r}
flattenCorrMatrix <- function(cormat, pmat) {
               ut <- upper.tri(cormat)
               data.frame(
               row = rownames(cormat)[row(cormat)[ut]],
               column = rownames(cormat)[col(cormat)[ut]],
               cor  =(cormat)[ut],
               p = pmat[ut]
               )
}

```

```{r}
c1=subset(nepith,  subtype=="N_Basal" & Condition=="Normal")
mat_c1= c1@assays$RNA@data
library(Hmisc)
res<-rcorr(as.matrix(mat_c1))
tmp <- flattenCorrMatrix(res$r, res$P)
tmp$clust="Normal_Basal"


c2=subset(nepith,  subtype=="N_LP" & Condition=="Normal")
mat_c1= c2@assays$RNA@data
library(Hmisc)
res<-rcorr(as.matrix(mat_c1))
tmp2 <- flattenCorrMatrix(res$r, res$P)
tmp2$clust="Normal_LP"


c3=subset(nepith,  subtype=="N_ML" & Condition=="Normal")
mat_c3= c3@assays$RNA@data
library(Hmisc)
res<-rcorr(as.matrix(mat_c3))
tmp3 <- flattenCorrMatrix(res$r, res$P)
tmp3$clust="Normal_ML"

c4=subset(nepith,  subtype=="N_LP" & Condition=="Normal BRCA1+/- pre-neoplastic")
mat_c4= c4@assays$RNA@data
library(Hmisc)
res<-rcorr(as.matrix(mat_c4))
tmp4 <- flattenCorrMatrix(res$r, res$P)
tmp4$clust="Mut_LP"



c5=subset(nepith,  subtype=="N_Basal" & Condition=="Normal BRCA1+/- pre-neoplastic")
mat_c5= c5@assays$RNA@data
library(Hmisc)
res<-rcorr(as.matrix(mat_c5))
tmp5 <- flattenCorrMatrix(res$r, res$P)
tmp5$clust="Mut_Basal"


c6=subset(nepith,  subtype=="N_ML" & Condition=="Normal BRCA1+/- pre-neoplastic")
mat_c6= c6@assays$RNA@data
library(Hmisc)
res<-rcorr(as.matrix(mat_c6))
tmp6 <- flattenCorrMatrix(res$r, res$P)
tmp6$clust="Mut_ML"


datcor=list(  "Normal_Basal"=tmp$cor, "Mut_Basal"=tmp5$cor, "Normal_LP"= tmp2$cor, "Mut_LP"= tmp4$cor,
"Normal_ML"= tmp3$cor, "Mut_ML"= tmp6$cor)       

res2 <- as.data.frame(do.call(cbind, datcor)) 

qs::qsave(res2, file.path(RDatadir,"PairwiseCorr_Epith_Conditions.qs"))


memory.limit(size= 100000)
raster_pdf(file.path(figDir,"EMBO_IntraCorr_EpithType_Condition.pdf"))
p <-  res2 %>%  reshape2::melt() %>%  ggplot() + 
  geom_violin(aes(x = variable, y = value, col= variable, fill= variable), show.legend = F) + 
  stat_summary(fun= median, geom='point', size = 3, colour = "black", shape = 95,aes(x = variable, y = value)) + ylab("pairwise_IntraClust_Correlation") + themplot

#+ scale_color_manual(values=epith_cols) + scale_fill_manual(values=epith_cols)
  print(p)
dev.off()

```

```{r}
res2=qs::qread(file.path(RDatadir,"PairwiseCorr_Epith_Conditions.qs"))

median(res2$Mut_Basal)/median(res2$Normal_Basal) #0.9996171
median(res2$Mut_LP)/median(res2$Normal_LP) #1.052493
median(res2$Mut_ML)/median(res2$Normal_ML) # 1.068389

library(ggpubr)
library(rstatix)

df=reshape2::melt(d)
d=res2[,1:2]


stat.test <- df %>%
  group_by(variable) %>%
  wilcox_test(value ~ variable) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")
stat.test
```


