---
title: "Step3_Juxta_EpitheCompartment_inferCNV"
author: "Melissa"
date: "18/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mainDir= mainDir= here::here()
inputDir= file.path(mainDir, "input", "human", "snRNAseq", "juxtaTumor","filtered_matrices")
outputDir= file.path(mainDir, "output", "human","snRNAseq", "juxtaTumor")
#####################
RDatadir <- file.path(outputDir,"RData") ; if(!file.exists(RDatadir)){dir.create(RDatadir)}
QCdir <- file.path(outputDir, "QC") ; if(!file.exists(QCdir)){dir.create(QCdir)}
DEdir <- file.path(outputDir, "DiffExp") ; if(!file.exists(DEdir)){dir.create(DEdir)}
clustDir= file.path(outputDir, "Clustering") ; if(!file.exists(clustDir)){dir.create(clustDir)}
cnvDir= file.path(outputDir, "CNV") ; if(!file.exists(cnvDir)){dir.create(cnvDir)}
```

check CNV ateration:
```{r}
juxta=qs::qread(paste0(RDatadir, "/Juxta_Integrated_Cohort1_Stroma.qs"))


 Sys.setenv(JAGS_HOME="C:\\Program Files\\JAGS\\JAGS-4.3.0")
library("rjags")
library(infercnv)
library(ChromSCape)
data("hg38.GeneTSS")
gene_annot = hg38.GeneTSS[,c(4,1,2,3)]
colnames(gene_annot) = NULL
rownames(gene_annot)= gene_annot[,1]
gene_annot=gene_annot[,c(2:4)]

Idents(juxta)="annotation"

cnv=Wrapper_inferCNV(juxta,ref_group= c("Endothelial", "Fibroblasts", "Immune"),outputPath=cnvDir, analysis_mode="samples",HMM_type="i3", gene_annot = gene_annot) 
qs::qsave(cnv, paste0(RDatadir, "/Seurat_CNV.qs"))

Wrapper_inferCNV= function( SeurObj,ref_group,outputPath, analysis_mode,HMM_type, gene_annot){
  
  message("Creation of the annotation object")
  
  #stopifnot( (str(type) %in% colnames(SeurObj@meta.data) ))
  
  annotation <- as.data.frame(SeurObj$annotation) %>% rownames_to_column() 
  rownames(annotation)= make.unique(annotation[,1])
 n <-rownames(annotation)
 annotation=as.data.frame(annotation[,-1], row.names = n); rm(n)
 names(annotation)=NULL
 counts_matrix <- as.matrix(SeurObj@assays$RNA@counts[,colnames(SeurObj)]) 
 
 message("Creation of the inferCNV object")
 
 cnv_Obj <-CreateInfercnvObject(counts_matrix, gene_order_file=gene_annot, annotations_file=annotation,
  max_cells_per_group = NULL,
  min_max_counts_per_cell = NULL,ref_group_names= ref_group)
 
 message("Running inferCNV is starting" )
 
 infercnv <- infercnv::run(
    cnv_Obj,
    min_cells_per_gene = 50,
    cutoff=0.1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
    out_dir=outputPath,
    cluster_references = FALSE,
    cluster_by_groups=TRUE, 
    denoise=TRUE,
    HMM=T,
    analysis_mode = analysis_mode,
    no_prelim_plot=FALSE,
    png_res=500,
   plot_steps=F,num_threads=1, HMM_type= HMM_type)
 
  message( "Adding the inferCNV output to the Seurat obj")
  
 SeurObj=add_to_seurat(
  seurat_obj = SeurObj,
  infercnv_output_path = outputPath,
  top_n = 50,
  bp_tolerance = 2e+06)
 
 return(SeurObj)
}
```

```{r}
obs3=read.table(file.path(cnvDir,"/infercnv.observations.txt")) %>% as.matrix()
colnames(obs3) = gsub("[.]1","-1", colnames(obs3))

lowthr <- quantile(obs3,0.01) #0.9120466 
highthr <- quantile(obs3,0.99)# 1.090948

tlg <- obs3 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0)))) %>% abs()

x= tlg %>% reshape2::melt() %>% dplyr::filter(value==1)
x=as.data.frame.matrix(table(x$variable, x$value))
colnames(x)= "alt"
x= apply(x,2, function(u){round(u/nrow(tlg), 3)} ) %>% as.data.frame()
x$cell <- rownames(x)
```

```{r}
ref3=read.table(file.path(cnvDir,"/infercnv.references.txt")) %>% as.matrix()
colnames(ref3) = gsub("[.]1","-1", colnames(ref3))

tlgr <- ref3 %>% as.data.frame() %>% mutate(across(everything(), ~  ifelse(. <=  lowthr, -1, ifelse(. >=  highthr, 1, 0)))) %>% abs()
####

xr= tlgr %>% reshape2::melt() %>% dplyr::filter(value==1)
xr=as.data.frame.matrix(table(xr$variable, xr$value))
colnames(xr)= "alt"
xr= apply(xr,2, function(u){round(u/nrow(tlgr), 3)} ) %>% as.data.frame()
xr$cell <- rownames(xr)

m= rbind(x, xr)
```

```{r}
m= m[match(colnames(juxta), m$cell),]
stopifnot(rownames(m)== colnames(juxta))
juxta$altered_Genome <- m$alt

qs::qsave(juxta,paste0(RDatadir, "/Juxta_Integrated_Cohort1_Stroma.qs"))
```

```{r}
m= m %>% dplyr::filter(cell %in% colnames(epithelial))
identical(m$cell, colnames(epithelial))
epithelial$altered_Genome=m$alt

png(paste0(clustDir, "/Epithelial_Altered_Genome_RefStroma2.png"))
p <- FeaturePlot(epithelial, features = "altered_Genome", pt.size = 1.5) + scale_color_viridis(option="B", direction = -1)
print(p)
dev.off()

png(paste0(clustDir, "/Epithelial_p16MouseSig.png"))
p <- FeaturePlot(epithelial, features = "p16sigM_UCell", pt.size = 1.5) + scale_color_viridis(option="B", direction = -1)
print(p)
dev.off()

png(paste0(clustDir, "/Epithelial_p16HumanSig.png"))
p <- FeaturePlot(epithelial, features = "p16sigH_UCell", pt.size = 1.5) + scale_color_viridis(option="B", direction = -1)
print(p)
dev.off()
```



```{r}
pdf(paste0(clustDir, "/Vln_Epithelial_Altered_Genome_WOBasal.pdf"))
p <- VlnPlot(epithelial, features = "altered_Genome", pt.size = 0, cols=cols_ep) +     stat_compare_means(ref.group = "LP_2", label = "p.signif", method = "wilcox.test") + stat_summary(fun.y=median, geom="point", size=2, color="black") + NoLegend()
print(p)
dev.off()

png(paste0(clustDir, "/Vln_Epithelial_p16Human1.png"), height = 1000, width = 1000, res=300)
p <- VlnPlot(epithelial, features = "p16sigH_UCell", pt.size = 0, cols=cols_ep) +     stat_compare_means(ref.group = "Basal", label = "p.signif", method = "wilcox.test") + stat_summary(fun.y=median, geom="point", size=2, color="black") + NoLegend()
print(p)
dev.off()

```

```{r}
pdf(paste0(clustDir, "/Vln_Epithelial_Altered_Genome1.pdf"))
p <- VlnPlot(epithelial, features = "altered_Genome", pt.size = 0, cols=cols_ep) +     stat_compare_means(ref.group = "Basal", label = "p.signif", method = "wilcox.test") + stat_summary(fun.y=median, geom="point", size=2, color="black") + NoLegend()
print(p)
dev.off()

pdf(paste0(clustDir, "/Vln_Epithelial_p16Human1.pdf"))
p <- VlnPlot(epithelial, features = "p16sigH_UCell", pt.size = 0, cols=cols_ep) +     stat_compare_means(ref.group = "Basal", label = "p.signif", method = "wilcox.test") + stat_summary(fun.y=median, geom="point", size=2, color="black") + NoLegend()
print(p)
dev.off()
```

