---
title: "Epigenome_mm_H3K4me1_2_Epithelial_Subset"
author: "Melissa"
date: "2025-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
archrDir="/Users/msaichi/Desktop/PROJECTS/epigenome_mm10_K4me1"
outputDir <- file.path(archrDir,"Figures_Epigenome") ; if(!file.exists(outputDir)){dir.create(outputDir)}

mainDir=here::here() #C:/Users/Melissa S/Desktop/PROJECTS/Spatial_Transcriptomics/MERFISH
inputDir= file.path(mainDir,"input", "mouse","snH3K4me1","Fragment_Files")
outputDir= file.path(mainDir,"output","mouse","snH3K4me1")

RDataDir <- file.path(outputDir,"RData") ; if(!file.exists(RDatadir)){dir.create(RDatadir)}
figDir= file.path(outputDir, "Figures") ; if(!file.exists(figDir)){dir.create(figDir)}
```

```{r}
gtheme= theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 0, hjust = 0.5),axis.text.y = element_text(size=12, face="bold", colour = "black"),legend.text = element_text(face = "bold", size = 12),text=element_text(size=14, face="bold", colour = "black"))
###
themplot=theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank())

'%!in%' <- function(x,y)!('%in%'(x,y))
```


```{r}
cols_hist=c("GCreP"="#1CAC78","CreN"= "#686D76", "CCI"="#A67B5B")
col_type=c("Basal"= "#a29cd5","LP"="#d96685", "H-S"="#f1c8cf","Tumor"= "#A67B5B", "Fibroblast2"="#94C6F7","Fibroblast3"= "#DEEFF7", "Fibroblast"= "#628ab8","Immune"= "#F2EBB1","Endothelial"= "#c09a17","Immune_Myeloid"=  "#C8C689" )
col_samples=c("#686D76","#50B498","#658147","#90D26D","#059212", "#A67B5B") #"#808836",
names(col_samples)= table(proj_20k$histology) %>% names()
```



###Isolate Epith from all:
```{r}
proj_20k=loadArchRProject("keptCells")
epith_all=subsetArchRProject(
  ArchRProj = proj_20k,
  cells = rownames(proj_20k@cellColData)[which(proj_20k$type %in% c("LP","H-S","Basal","Tumor"))],
  outputDirectory = "All_Epith",
  dropCells = TRUE,
  logFile = NULL,
  threads = 1,
  force = TRUE)
epith_all=downstream(epith_all)

epith_all<- addUMAP(ArchRProj = epith_all, force = T, reducedDims = "IterativeLSI",nNeighbors = 20)
saveArchRProject(ArchRProj = epith_all, outputDirectory = "All_Epith", load = FALSE)

```

```{r}
df <- getEmbedding(ArchRProj  = epith_all, embedding = "UMAP")
df <- cbind(df,epith_all@cellColData)
colnames(df) <- c("UMAP_1","UMAP_2", colnames(df)[-c(1,2)])
###
 p= df %>%  ggplot(aes(x= UMAP_1, y=UMAP_2, fill= type)) + geom_point(shape = 21, colour="black", stroke=0.7, size=2,alpha=0.8) + scale_fill_manual(values = col_type) + themplot + NoLegend()
 
 pdf(file.path(figDir, "UMAP_EPITH_All_Type.pdf"), height = 8, width = 8)
print(p)
dev.off()

 cols=c("CreN_1"="#808080f2" , "T_7879_mm_m11y22"="#774946ff" , "C_7412_mm_m02y22"="#e4f3c2ff" , "G_7797_J7789_7790_mm_m11y22"= "#d5c775ff", "J_7583_mm_m06y22_1"= "#d2eb9dff","J_7584_mm_m06y22"= "#cde599ff")

 p= df %>% BuenColors::shuf() %>%  ggplot(aes(x= UMAP_1, y=UMAP_2, fill= Sample)) + geom_point(shape = 21, colour="black", stroke=0.7, size=2,alpha=0.8) + scale_fill_manual(values = cols) + themplot + NoLegend()

 pdf(file.path(figDir, "UMAP_EPITH_All_Sample.pdf"), height = 8, width = 8)
print(p)
dev.off()


png(file.path(figDir, "UMAP_EPITH_All_Sample.png"), height = 1500, width = 1500, res = 300)
print(p)
dev.off()

p= df %>% BuenColors::shuf() %>%  ggplot(aes(x= UMAP_1, y=UMAP_2, fill= hist)) + geom_point(shape = 21, colour="black", stroke=0.7, size=2,alpha=0.8) + scale_fill_manual(values = cols_hist) + themplot + NoLegend()
png(file.path(figDir, "UMAP_EPITH_All_Hist.png"), height = 1500, width = 1500, res = 300)
print(p)
dev.off()

p= df %>% BuenColors::shuf() %>% ggplot(aes(x= UMAP_1, y=UMAP_2, fill= type)) + geom_point(shape = 21, colour="black", stroke=0.7, size=2,alpha=0.8) + scale_fill_manual(values = col_type) + themplot + NoLegend()
png(file.path(figDir, "UMAP_EPITH_All_TYPE_Wo_cren1.png"), height = 1500, width = 1500, res = 300)
print(p)
dev.off()
```

Generate 2D plots of the cren Basal and LP signatures:

#### add signatures of creN on crep and cci
```{r}
epith_creN=subsetArchRProject(
  ArchRProj = creN,
  cells = rownames(creN@cellColData)[which(creN$type %in% c("LP","H-S","Basal"))],
  outputDirectory = "creN_Epith",
  dropCells = TRUE,
  logFile = NULL,
  threads = 1,
  force = TRUE)
epith_creN=downstream(epith_creN)

saveArchRProject(ArchRProj = epith_creN, outputDirectory = "creN_Epith", load = FALSE)
```

```{r}
df <- getEmbedding(ArchRProj  = epith_creN, embedding = "UMAP")
df <- cbind(df, epith_creN@cellColData)
colnames(df) <- c("UMAP_1","UMAP_2", colnames(df)[-c(1,2)])

p= df %>% ggplot(aes(x= UMAP_1, y=UMAP_2, fill= type)) + geom_point(shape = 21, colour="black", stroke=0.7, size=2,alpha=0.8) + scale_fill_manual(values = col_type) + themplot + NoLegend()

png(file.path(figDir, "Final_UMAP_creN_EPITH_Type_woCreN1.png"), height = 1200, width = 1200, res = 300)
print(p)
dev.off()
```

USE EPIGENOME SIGNATURES:
```{r}
markersGSCreN <- getMarkerFeatures(
    ArchRProj = epith_creN, 
    useMatrix = "GeneScoreMatrix", 
    groupBy = "type",
    bias = c("TSSEnrichment", "nFrags"),
    testMethod = "wilcoxon")
markerListCreN <- getMarkers(markersGSCreN, cutOff = "Pval <= 0.05 & Log2FC >= 0")

features= lapply(markerListCreN, function(x) { x %>% as.data.frame() %>%  arrange(desc(Log2FC)) %>% filter(Log2FC > quantile(Log2FC, 0.85)) %>% dplyr::select(name) %>% unlist()})

### ON CREN:
gm= ArchR::getMatrixFromProject(epith_creN, useMatrix = "GeneScoreMatrix")
mat= assay(gm)
rownames(mat)=rowData(gm)$name
colnames(mat)=gm@colData@rownames

#########
sigN=  UCell::ScoreSignatures_UCell(as.matrix(mat), features = features,  maxRank = 3000) %>% as.data.frame()
identical(rownames(sigN),epith_creN$cellNames)

sigN$type=epith_creN$type

p=ggtern(data=sigN,aes(x=Basal_UCell,y=LP_UCell, z=`H-S_UCell`, color = type, group = type)) +geom_point(alpha = 0.5,position = position_nudge_tern(x = 0.1, y = 0.1, z = 0.1))+
  theme_classic()
######
### ON CREN:
gm= ArchR::getMatrixFromProject(epith_creP, useMatrix = "GeneScoreMatrix")
matp= assay(gm)
rownames(matp)=rowData(gm)$name
colnames(matp)=gm@colData@rownames

#########
sigP=  UCell::ScoreSignatures_UCell(as.matrix(matp), features = features,  maxRank = 3000) %>% as.data.frame()
identical(rownames(sigP),epith_creP$cellNames)
sigP=sigP[epith_creP$cellNames,]
sigP$type=epith_creP$type

p=ggtern(data=sigP,aes(x=Basal_UCell,y=LP_UCell, z=`H-S_UCell`, color = type, group = type)) +geom_point(alpha = 0.5,position = position_nudge_tern(x = 0.1, y = 0.1, z = 0.1))+
  theme_classic()
```

##Isolate Epith from CreP:
```{r}
epith_creP=subsetArchRProject(
  ArchRProj = creP,
  cells = rownames(creP@cellColData)[which(creP$type %in% c("LP","H-S","Basal","Tumor"))],
  outputDirectory = "creP_Epith",
  dropCells = TRUE,
  logFile = NULL,
  threads = 1,
  force = TRUE)
epith_creP=downstream(epith_creP)

saveArchRProject(ArchRProj = epith_creP, outputDirectory = "creP_Epith", load = FALSE)
```



```{r}
epith_creP=addImputeWeights(epith_creP, reducedDims = "IterativeLSI")
gm= ArchR::getMatrixFromProject(epith_creP, useMatrix = "GeneScoreMatrix")
mat= imputeMatrix(assay(gm), getImputeWeights(epith_creP))

rownames(mat)=rowData(gm)$name
colnames(mat)=gm@colData@rownames
#mat=as.matrix(assay(gm))
sig=  UCell::ScoreSignatures_UCell(as.matrix(mat), features = features,  maxRank = 3000)
identical(rownames(sig),epith_creP$cellNames)
sig=sig[epith_creP$cellNames,]
  epith_creP$creN_Basal= sig[,1]
  epith_creP$creN_LP=  sig[,3]
  epith_creP$creN_ML= sig[,2]
```

```{r}
dat_tern <- as.data.frame(sig)
colnames(dat_tern)=gsub("_UCell","", colnames(dat_tern))

identical(rownames(dat_tern), epith_creP$cellNames)
dat_tern$type <- epith_creP$type
dat_tern$hist <- epith_creP$hist
qs::qsave(dat_tern, file.path(RDataDir, "Signatures_EpithCreN_onCreP.qs"))
dat_tern=qs::qread(file.path(RDataDir, "Signatures_EpithCreN_onCreP.qs"))

crep= dat_tern %>% dplyr::filter(hist=="GCreP")
crep=crep %>% dplyr::filter(! type== "Tumor")

cci= dat_tern %>% dplyr::filter(hist=="CCI")
cci=cci %>% dplyr::filter(! type %in% c("LP","H-S"))
##########
g=cci %>% ggplot(aes(x= LP,y=Basal,fill = type )) + geom_point( shape = 21, colour="black", stroke=0.7, size=2,alpha=0.8) + scale_fill_manual(values=col_type) + theme_classic() + NoLegend() + scale_y_continuous(limits=c(0, 0.11)) + scale_x_continuous(limits=c(0, 0.07))
png(file.path(figDir, "2D_CCI.png"), height = 1500, width = 1500, res = 300)
print(g)
dev.off()
######################
crep$type=factor(crep$type, levels= c("LP" ,"Basal","H-S"))
p2=ggplot(crep %>% arrange(type),aes(x= LP,y=Basal,fill = type )) + geom_jitter( shape = 21, colour="black", stroke=0.7, size=2,alpha=0.8,width = 0.001) + scale_fill_manual(values=col_type) + theme_classic() + NoLegend()

png(file.path(figDir, "Final2D_CREP.png"), height = 1500, width = 1500, res = 300)
print(p2)
dev.off()

```
