---
title: "PC_informativity_Functions"
author: "Melissa"
date: "19/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(knitr::purl(file.path(mainDir,"Scripts","scRNAseq_Functions.Rmd"), quiet=TRUE))
source(knitr::purl(file.path(mainDir,"Scripts","global_variables.Rmd"), quiet=TRUE))
```

```{r}
inputDir= file.path(mainDir,"input" ,"human","scRNAseq","publicDatasets","input_GSE161529")
outputDir= file.path(mainDir, "output","human","public_data","EMBO")
###
plotDir= file.path(outputDir,"Plots") ; if(!file.exists(plotDir)){dir.create(plotDir)}
RdataDir= file.path(outputDir,"Rdata") ; if(!file.exists(RdataDir)){dir.create(RdataDir)}
cnvDir=  file.path(outputDir,"inferCNV") ; if(!file.exists(cnvDir)){dir.create(cnvDir)}

gtheme= theme (axis.text.x = element_text(size=12, face="bold", colour = "black", angle = 0, hjust = 0.5),axis.text.y = element_text(size=12, face="bold", colour = "black"),legend.text = element_text(face = "bold", size = 12),text=element_text(size=14, face="bold", colour = "black"))
###
themplot=theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank())
```

```{r}
PC_separability= function(obj, nPCs, subtype){
  
  message("get the PCA embeddings from the Seurat Object")
  stopifnot( "pca" %in% Reductions(obj))
  
  pc <- Embeddings(obj, reduction = "pca")[, 1:nPCs] %>% as.data.frame()
  identical(rownames(pc), rownames(obj@meta.data))
  pc$condition= obj$Condition
  
  restest= data.frame("PC"= paste0("PC_", seq_len(nPCs)), "KStest"= NA, "Dvalue"=NA, "MedianDiff"=NA)
  
  
   pdf(paste0(pcDir, "/Density_Distrib_Normal_Preneo_",subtype ,".pdf"), height = 7, width = 7)
  for( i in seq_len(nPCs)){
    
    message("compare density distribution across the PCs using KS test")
    
    restest[i,2]= ks.test(pc[which(pc$condition== "Normal"), i], y=pc[which(pc$condition=="Normal BRCA1+/- pre-neoplastic"), i])$p.value
    
     restest[i,3]= ks.test(pc[which(pc$condition== "Normal"), i], y=pc[which(pc$condition=="Normal BRCA1+/- pre-neoplastic"), i])$statistic
    
     message("Adding median value ")
     restest[i,4]= median(pc[which(pc$condition== "Normal BRCA1+/- pre-neoplastic"), i]) - median(pc[which(pc$condition== "Normal"), i])
     
     message("plotting the density distribution of the PC_", i)
    
   
      p <- ggplot(pc, aes(fill= condition,x= pc[,i])) +
      geom_density(alpha=0.4) + scale_fill_manual(values=rev(met.brewer(name="Egypt",n=4,type="discrete"))[c(2,1)]) + themplot +  xlab(paste("PC_",i, "KS_test=", restest[i,2])) + theme(legend.position = "none")
      print(p)
     

  }
   dev.off()
  return(restest)
}
```

Method2:
```{r}
PC_separability_lm= function(obj, nPCs){
pc <- Embeddings(obj, reduction = "pca")[, 1:nPCs] %>% as.data.frame()
  identical(rownames(pc), rownames(obj@meta.data))
  pc$condition= obj$Condition
  
dt.lm= data.frame("PC"= paste0("PC_", seq_len(nPCs)), "Rsquare"=NA , "pval"=NA)
for( i in seq_len(nPCs)){
  dt.lm[i,2]=summary( lm( pc[, i] ~ pc[,ncol(pc)] ))$r.squared
  dt.lm[i,3]=summary( lm( pc[, i] ~ pc[,ncol(pc)] ))$coefficients[2,4]
}

return(dt.lm)
}
```


```{r}
##################### FOR DIFF EXPRESSION ##############

PC_important_PEA= function(obj, dtest, subtype){
    m_t2g <- msigdbr::msigdbr(species = "Homo sapiens", category = "H") %>% dplyr::select(gs_name, gene_symbol) %>% as.data.frame()
  pcs= dtest %>% dplyr::filter(Informativity=="Informative")
  pcs_LP= gsub("PC_","",pcs[,1]) %>% as.numeric()
  pcs_LP= pcs_LP[which(pcs_LP < 20)]

for( i in pcs_LP) {
  
  tmp1 <- obj@reductions$pca@feature.loadings[,i] %>% as.data.frame() %>% rownames_to_column("gene")
  colnames(tmp1)= c("gene","eigen")
  
  tmp1n = tmp1 %>% dplyr::filter(eigen < (-0.015)) 
  
 
  
 pean= clusterProfiler::enricher(tmp1n$gene , TERM2GENE=m_t2g) @result %>% dplyr::filter(., p.adjust< 0.01)%>% .[,c(1,6,8)]
pean$geneID= gsub("/",",", pean$geneID)
########################################%>% dplyr::filter(! gene %in% grep("^IG", tmp1p$gene, value = TRUE))
 tmp1p = tmp1 %>% dplyr::filter(eigen > (0.015)) 
peap=  clusterProfiler::enricher(tmp1p$gene , TERM2GENE=m_t2g) @result %>% dplyr::filter(., p.adjust< 0.01)%>% .[,c(1,6,8)]
peap$geneID= gsub("/",",", peap$geneID)


 sl= list(pean, peap)
 names(sl)= c(paste0("contrib_Neg_PC",i), paste0("contrib_Pos_PC",i))
 
 writexl::write_xlsx(sl, paste0(pcDir, "/PEA_", subtype,"_H_PC_", i,".xlsx"))
} 
 return(sl)
}
```

