---
title: "Step1_TCGA_Normalization"
author: "Melissa"
date: "04/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
mainDir <- here::here() # the MainDir should be the root of Tumor_BRCA_P53:
source(knitr::purl(file.path(mainDir,"Scripts","scRNAseq","mouse","TCGA","Global_Variables_TCGA.Rmd"), quiet=TRUE))
```


##------------- LOAD THE METADATA, downloaded from C BIO PORTAL -----------------###

```{r}
tcga_br <- read.delim(paste0(inputDir,"/brca_tcga_pan_can_atlas_2018_clinical_data.tsv")) %>% as.data.frame()
```



###--------------------------------- WORK ON THE LOADED TCGA DATA ----------------------------####
```{r}
BRCARnaseqSE <- qs::qread(paste0(inputDir, "/BRCARnaseqSE_initialData.qs"))
BRCAMatrix <- assay(BRCARnaseqSE,"raw_count")
```



To make sure the metadata and expression matreix matches, do the following:
```{r}
smp <- stringi::stri_sub(colnames(BRCAMatrix), from = 0, to= 15)
length(intersect(smp, tcga_br$Sample.ID)) #1081
##
rm(smp)
colnames(BRCAMatrix)=stringi::stri_sub(colnames(BRCAMatrix), from = 0, to= 15)
##

tcga_br = tcga_br %>% dplyr::filter(Sample.ID %in% colnames(BRCAMatrix))
stopifnot(identical(tcga_br$Sample.ID, colnames(BRCAMatrix)))
BRCAMatrix=BRCAMatrix[, tcga_br$Sample.ID]

tcga_br$Subtype= ifelse(is.na(tcga_br$Subtype)== TRUE, "Undefined", tcga_br$Subtype)
tcga_br$Neoplasm.Disease.Stage.American.Joint.Committee.on.Cancer.Code= ifelse(is.na(tcga_br$Neoplasm.Disease.Stage.American.Joint.Committee.on.Cancer.Code)== TRUE, "Undefined", tcga_br$Neoplasm.Disease.Stage.American.Joint.Committee.on.Cancer.Code)
###
plyr::count(tcga_br$Subtype)
```

```{r}
writexl::write_xlsx(tcga_br, paste0(inputDir, "/Processed_Metadata.xlsx"))
```


###------------- PERFORM NORMALIZATION: BASAL-LIKE vs ALL samples ------###
```{r}
BRCAMatrix= round(as.matrix(BRCAMatrix))
rownames(BRCAMatrix)=gsub("\\|.*", "", rownames(BRCAMatrix)) 
####
tcga_br$sub= tcga_br$Subtype
tcga_br$sub= ifelse(tcga_br$sub=="BRCA_Basal", "BRCA_Basal", "Others")
##

dds <- DESeqDataSetFromMatrix(countData=BRCAMatrix, colData = tcga_br, design = ~ sub)
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]
dds <- DESeq(dds)
## SAVE THE DIFF EXPRESSION DESEQ OBJECT:
qs::qsave(dds, paste0(RDatadir, "/DESEQ_Object_Basal_vsAll.qs"))
```

